export const HOME_GET_POST_LIST = 'HOME_GET_POST_LIST';
export const HOME_GET_POST_LIST_SUCCESS = 'HOME_GET_POST_LIST_SUCCESS';
export const HOME_GET_POST_LIST_ERROR = 'HOME_GET_POST_LIST_ERROR';
export const HOME_GET_POST_LIST_NONE = 'HOME_GET_POST_LIST_NONE';
